#!/bin/bash

set -ex

source environment

gce_wsk() { wsk -i --apihost $OW_GCE_APIHOST $*; }
aws_wsk() { wsk -i --apihost $OW_AWS_APIHOST $*; }
azr_wsk() { wsk -i --apihost $OW_AZR_APIHOST $*; }

S3_BUCKET=ayers-images
TRIGGER_NAME=ayersTrigger
RULE_NAME=ayersRule
ACTION_NAME=ayers

# XXX: there's no 'trigger get --url' similar to 'action get --url'
GCE_WEBHOOK=https://openwhisk-openwhisk.apps.summit-gce.sysdeseng.com/api/v1/namespaces/_/triggers/$TRIGGER_NAME
GCE_AUTH=$(gce_wsk property get --auth | awk '{print $3}')

# XXX: there's no 'trigger get --url' similar to 'action get --url'
AWS_WEBHOOK=https://openwhisk-openwhisk.apps.summit-aws.sysdeseng.com/api/v1/namespaces/_/triggers/$TRIGGER_NAME
AWS_AUTH=$(aws_wsk property get --auth | awk '{print $3}')

mvn clean test package -DskipTests

# GCE
gce_wsk action update $ACTION_NAME target/ayers-1.0-SNAPSHOT.jar --main com.redhat.summit2018.Action -p modelEndpoint $MODEL_ENDPOINT
# XXX: trigger update does not create a trigger, it is inconsistent w/ action update and rule update
gce_wsk trigger delete $TRIGGER_NAME && :
gce_wsk trigger create $TRIGGER_NAME
gce_wsk rule update $RULE_NAME $TRIGGER_NAME $ACTION_NAME
curl -X PUT -H "X-Auth-Token: $S3_GCE_AUTH" -H "X-Webhook: $GCE_WEBHOOK" -H "X-Webhook-Auth: $GCE_AUTH" http://$S3_GCE_HOST/v1/AUTH_gv0/$S3_BUCKET

# AWS
aws_wsk action update $ACTION_NAME target/ayers-1.0-SNAPSHOT.jar --main com.redhat.summit2018.Action -p modelEndpoint $MODEL_ENDPOINT
# XXX: trigger update does not create a trigger, it is inconsistent w/ action update and rule update
aws_wsk trigger delete $TRIGGER_NAME && :
aws_wsk trigger create $TRIGGER_NAME
aws_wsk rule update $RULE_NAME $TRIGGER_NAME $ACTION_NAME
curl -X PUT -H "X-Auth-Token: $S3_AWS_AUTH" -H "X-Webhook: $AWS_WEBHOOK" -H "X-Webhook-Auth: $AWS_AUTH" http://$S3_AWS_HOST/v1/AUTH_gv0/$S3_BUCKET

# AZR
azr_wsk action update $ACTION_NAME target/ayers-1.0-SNAPSHOT.jar --main com.redhat.summit2018.Action -p modelEndpoint $MODEL_ENDPOINT
# XXX: trigger update does not create a trigger, it is inconsistent w/ action update and rule update
azr_wsk trigger delete $TRIGGER_NAME && :
azr_wsk trigger create $TRIGGER_NAME
azr_wsk rule update $RULE_NAME $TRIGGER_NAME $ACTION_NAME
# TODO: S3 on Azure
#curl -X PUT -H "X-Auth-Token: $S3_AZR_AUTH" -H "X-Webhook: $AZR_WEBHOOK" -H "X-Webhook-Auth: $AZR_AUTH" http://$S3_AZR_HOST/v1/AUTH_gv0/$S3_BUCKET
